parameters:
    # +++ Class definitions +++
    filesystem.class: Symfony\Component\Filesystem\Filesystem


services:

    # +++ General services +++
    filesystem:
            class: "%filesystem.class%"